// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chat.Try.Context.Models
{
    public partial class Counter
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int Count { get; set; }
    }
}