// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chat.Try.Db.Models
{
    public partial class ConversationUsers
    {
        public ConversationUsers()
        {
            UserMessages = new HashSet<UserMessages>();
        }

        public int Id { get; set; }
        public int ConversationId { get; set; }
        public string UserId { get; set; }
        public DateTimeOffset CreatedOn { get; set; }

        public virtual Conversations Conversation { get; set; }
        public virtual AspNetUsers User { get; set; }
        public virtual ICollection<UserMessages> UserMessages { get; set; }
    }
}