// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chat.Try.Db.Models
{
    public partial class ReadReceipts
    {
        public int Id { get; set; }
        public int UserMessageId { get; set; }
        public int ConversationUserId { get; set; }
        public DateTimeOffset CreatedOn { get; set; }

        public virtual UserMessages UserMessage { get; set; }
    }
}