// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chat.Try.Db.Models
{
    public partial class UserMessages
    {
        public int Id { get; set; }
        public int ConversationUserId { get; set; }
        public string Message { get; set; }
        public DateTimeOffset CreatedOn { get; set; }

        public virtual ConversationUsers ConversationUser { get; set; }
    }
}