// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fennorad.Db.Models
{
    public partial class Conversations
    {
        public Conversations()
        {
            ConversationUsers = new HashSet<ConversationUsers>();
        }

        public int Id { get; set; }
        public DateTimeOffset CreatedOn { get; set; }

        public virtual ICollection<ConversationUsers> ConversationUsers { get; set; }
    }
}